baseURL = "https://losalamosal.me"
DefaultContentLanguage = "en"
title = "Los Alamos Al"
theme = "beautifulhugo"
buildDrafts = true
googleAnalytics = "UA-120820279-1"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
# pygmentsStyle = "manni"
pygmentsStyle = "murphy"
# pygmentsStyle = "pastie"
# pygmentsStyle = "colorful"
# pygmentsStyle = "autumn"
# pygmentsStyle = "monokai"
# pygmentsStyle = "emacs"
# pygmentsStyle = "friendly"
# pygmentsStyle = "native"
# pygmentsUseClasses = false

[Params]
  subtitle = "Semi-retired computer scientist. Prepping for the killer app."
  logo = "img/slim1.jpg"
  dateFormat = "January 2, 2006"
  readingTime = false
  mainSections = ["post","posts"]

[Author]
  name = "Allen McPherson"
  website = "losalamosal.me"
  email = "al@losalamosal.me"
  github = "losalamosal"
  twitter = "losalamosal"
  linkedin = "allenmcpherson"
  stackoverflow = "users/227441/los-alamos-al"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
